### ISSUE TITLE
readline Modul on Windows

### ISSUE THREAD

**Issue by fuuddanni** [Hypsurus/GICO#2]
Get following error:
E:\Github\Gico_GeoIP\Gico_GeoIP>pip install readline
Collecting readline
  Using cached readline-6.2.4.1.tar.gz
    Complete output from command python setup.py egg_info:
    error: this module is not meant to work on Windows

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\besitzer\appdata\local\temp\pip-build-inpw9m\readline\

E:\Github\Gico_GeoIP\Gico_GeoIP>cd ..

E:\Github\Gico_GeoIP>python2 gico.py
Traceback (most recent call last):
  File "gico.py", line 25, in <module>
    from lib.MyShell import myshell
  File "E:\Github\Gico_GeoIP\lib\MyShell\myshell.py", line 19, in <module>
    import readline
ImportError: No module named readline

E:\Github\Gico_GeoIP>

**Comment by Hypsurus** [comment]
No support for windows.

**Comment by Hypsurus** [comment]
No support for windows.

**Comment by Hypsurus** [comment]
No support for windows.

**Comment by Hypsurus** [comment]
No support for windows.

**Comment by Hypsurus** [comment]
No support for windows.

**Comment by Hypsurus** [comment]
No support for windows.

**Comment by Hypsurus** [comment]
No support for windows.

**Comment by Hypsurus** [comment]
No support for windows.

**Comment by Hypsurus** [comment]
No support for windows.

**Comment by Hypsurus** [comment]
No support for windows.

**Comment by Hypsurus** [comment]
No support for windows.

**Comment by fuuddanni** [comment]
Okay, thx you. What about http://stackoverflow.com/questions/6024952/readline-functionality-on-windows-with-python-2-7 .

**Comment by Hypsurus** [comment]
If I will add support for windows It will be without auto-complete!!
